# Other imports.
from StudentClass import Student

def populate():
	students = []
	students.append(Student(email="jiahao_xu@brown.edu", area="Systems"))
	students.append(Student(email="fumi_honda@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="andrew_levy2@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="fatma_esen_erdemgil@brown.edu")	)
	students.append(Student(email="yang_zhang2@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="sydney_zink@brown.edu", area="Natural Language Processing"))
	students.append(Student(email="won_jun_kang@brown.edu", area="Data Science"))
	students.append(Student(email="yuchen_yang@brown.edu", area="Systems"))
	students.append(Student(email="cameron_s_allen@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="jason_ludmir@brown.edu"))
	students.append(Student(email="cyrus_cousins@brown.edu", area="Systems"))
	students.append(Student(email="noah_picard@brown.edu", area="Computer Vision"))
	students.append(Student(email="xinyu_liu@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="kaiyu_zheng@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="david_abel@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="jiahao_yuan@brown.edu"))
	students.append(Student(email="archer_wheeler@brown.edu", area="Algorithms and Theory"))
	students.append(Student(email="wensi_you@brown.edu", area="Systems"))
	students.append(Student(email="yanyan_ren@brown.edu", area="Computing Education"))
	students.append(Student(email="saim_salman@brown.edu", area="Systems"))
	students.append(Student(email="ifrah_idrees@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="qiao_zhang@brown.edu"))
	students.append(Student(email="michael_snower@brown.edu"))
	students.append(Student(email="junjay_tan@brown.edu", area="Systems"))
	students.append(Student(email="thao_nguyen3@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="christine_yu@brown.edu")	)
	students.append(Student(email="marilyn_george@brown.edu", area="Security and Cryptography"))
	students.append(Student(email="xiaodong_zhang@brown.edu"))
	students.append(Student(email="amariah_becker@brown.edu", area="Algorithms and Theory"))
	students.append(Student(email="theresa_barton@brown.edu", area="Computer Vision"))
	students.append(Student(email="akhil_bagaria@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="david_smith1@brown.edu"))
	students.append(Student(email="ruochen_zhang@brown.edu", area="Data Science"))
	students.append(Student(email="maha_alrasheed@brown.edu", area="Security and Cryptography"))
	students.append(Student(email="eric_rosen@brown.edu", area="AI/ML/Robotics"))
	students.append(Student(email="yingjie_xue@brown.edu", area="Security and Cryptography"))
	students.append(Student(email="yuanning_hu@brown.edu"))
	students.append(Student(email="changmin_teng@brown.edu"))
	students.append(Student(email="shashwat_sinha@brown.edu"))
	students.append(Student(email="shaili_jha@brown.edu"))

	return students